owner: tjorim
repo: upptime

sites:
  - name: Champagne Festival
    url: https://champagnefestival.tjor.im
  - name: Champagne Festival API
    url: $CHAMPAGNEFESTIVAL_API_URL
  - name: Champagne Festival end-to-end
    url: $CHAMPAGNEFESTIVAL_E2E_URL
  - name: Worktime
    url: https://worktime.tjor.im
  - name: Worktime API
    url: $WORKTIME_API_URL
  - name: SuperTokens
    url: $AUTHENTICATION_URL

status-website:
  baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/tjorim
  name: tjor.im status
  introTitle: "**tjor.im** service status"
  introMessage: Real-time uptime monitoring for tjor.im services, powered by GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
